using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IntegradorSAP.Data.Models
{
   
    public class ItemsViewModel
    {
        //public string odatametadata { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ForeignName { get; set; }
        public int ItemsGroupCode { get; set; }
        public int CustomsGroupCode { get; set; }
        public string SalesVATGroup { get; set; }
        public object BarCode { get; set; }
        public string VatLiable { get; set; }
        public string PurchaseItem { get; set; }
        public string SalesItem { get; set; }
        public string InventoryItem { get; set; }
        public object IncomeAccount { get; set; }
        public object ExemptIncomeAccount { get; set; }
        public object ExpanseAccount { get; set; }
        public string Mainsupplier { get; set; }
        public object SupplierCatalogNo { get; set; }
        public float DesiredInventory { get; set; }
        public float MinInventory { get; set; }
        public object Picture { get; set; }
        public object User_Text { get; set; }
        public object SerialNum { get; set; }
        public float CommissionPercent { get; set; }
        public float CommissionSum { get; set; }
        public int CommissionGroup { get; set; }
        public string TreeType { get; set; }
        public string AssetItem { get; set; }
        public object DataExportCode { get; set; }
        public int Manufacturer { get; set; }
        public float QuantityOnStock { get; set; }
        public float QuantityOrderedFromVendors { get; set; }
        public float QuantityOrderedByCustomers { get; set; }
        public string ManageSerialNumbers { get; set; }
        public string ManageBatchNumbers { get; set; }
        public string Valid { get; set; }
        public string ValidFrom { get; set; }
        public object ValidTo { get; set; }
        public object ValidRemarks { get; set; }
        public string Frozen { get; set; }
        public object FrozenFrom { get; set; }
        public object FrozenTo { get; set; }
        public object FrozenRemarks { get; set; }
        public string SalesUnit { get; set; }
        public float SalesItemsPerUnit { get; set; }
        public object SalesPackagingUnit { get; set; }
        public float SalesQtyPerPackUnit { get; set; }
        public object SalesUnitLength { get; set; }
        public object SalesLengthUnit { get; set; }
        public object SalesUnitWidth { get; set; }
        public object SalesWidthUnit { get; set; }
        public object SalesUnitHeight { get; set; }
        public object SalesHeightUnit { get; set; }
        public float SalesUnitVolume { get; set; }
        public int SalesVolumeUnit { get; set; }
        public object SalesUnitWeight { get; set; }
        public object SalesWeightUnit { get; set; }
        public string PurchaseUnit { get; set; }
        public float PurchaseItemsPerUnit { get; set; }
        public object PurchasePackagingUnit { get; set; }
        public float PurchaseQtyPerPackUnit { get; set; }
        public object PurchaseUnitLength { get; set; }
        public object PurchaseLengthUnit { get; set; }
        public object PurchaseUnitWidth { get; set; }
        public object PurchaseWidthUnit { get; set; }
        public object PurchaseUnitHeight { get; set; }
        public object PurchaseHeightUnit { get; set; }
        public float PurchaseUnitVolume { get; set; }
        public int PurchaseVolumeUnit { get; set; }
        public object PurchaseUnitWeight { get; set; }
        public object PurchaseWeightUnit { get; set; }
        public string PurchaseVATGroup { get; set; }
        public float SalesFactor1 { get; set; }
        public float SalesFactor2 { get; set; }
        public float SalesFactor3 { get; set; }
        public float SalesFactor4 { get; set; }
        public float PurchaseFactor1 { get; set; }
        public float PurchaseFactor2 { get; set; }
        public float PurchaseFactor3 { get; set; }
        public float PurchaseFactor4 { get; set; }
        public float MovingAveragePrice { get; set; }
        public object ForeignRevenuesAccount { get; set; }
        public object ECRevenuesAccount { get; set; }
        public object ForeignExpensesAccount { get; set; }
        public object ECExpensesAccount { get; set; }
        public float AvgStdPrice { get; set; }
        public object DefaultWarehouse { get; set; }
        public object ShipType { get; set; }
        public string GLMethod { get; set; }
        public string TaxType { get; set; }
        public float MaxInventory { get; set; }
        public string ManageStockByWarehouse { get; set; }
        public object PurchaseHeightUnit1 { get; set; }
        public object PurchaseUnitHeight1 { get; set; }
        public object PurchaseLengthUnit1 { get; set; }
        public object PurchaseUnitLength1 { get; set; }
        public object PurchaseWeightUnit1 { get; set; }
        public object PurchaseUnitWeight1 { get; set; }
        public object PurchaseWidthUnit1 { get; set; }
        public object PurchaseUnitWidth1 { get; set; }
        public object SalesHeightUnit1 { get; set; }
        public object SalesUnitHeight1 { get; set; }
        public object SalesLengthUnit1 { get; set; }
        public object SalesUnitLength1 { get; set; }
        public object SalesWeightUnit1 { get; set; }
        public object SalesUnitWeight1 { get; set; }
        public object SalesWidthUnit1 { get; set; }
        public object SalesUnitWidth1 { get; set; }
        public string ForceSelectionOfSerialNumber { get; set; }
        public string ManageSerialNumbersOnReleaseOnly { get; set; }
        public string WTLiable { get; set; }
        public string CostAccountingMethod { get; set; }
        public object SWW { get; set; }
        public string WarrantyTemplate { get; set; }
        public string IndirectTax { get; set; }
        public object ArTaxCode { get; set; }
        public object ApTaxCode { get; set; }
        public object BaseUnitName { get; set; }
        public object ItemCountryOrg { get; set; }
        public string IssueMethod { get; set; }
        public string SRIAndBatchManageMethod { get; set; }
        public string IsPhantom { get; set; }
        public string InventoryUOM { get; set; }
        public string PlanningSystem { get; set; }
        public string ProcurementMethod { get; set; }
        public string ComponentWarehouse { get; set; }
        public object OrderIntervals { get; set; }
        public float OrderMultiple { get; set; }
        public object LeadTime { get; set; }
        public float MinOrderQuantity { get; set; }
        public string ItemType { get; set; }
        public string ItemClass { get; set; }
        public int OutgoingServiceCode { get; set; }
        public int IncomingServiceCode { get; set; }
        public int ServiceGroup { get; set; }
        public int NCMCode { get; set; }
        public string MaterialType { get; set; }
        public int MaterialGroup { get; set; }
        public string ProductSource { get; set; }
        public string Properties1 { get; set; }
        public string Properties2 { get; set; }
        public string Properties3 { get; set; }
        public string Properties4 { get; set; }
        public string Properties5 { get; set; }
        public string Properties6 { get; set; }
        public string Properties7 { get; set; }
        public string Properties8 { get; set; }
        public string Properties9 { get; set; }
        public string Properties10 { get; set; }
        public string Properties11 { get; set; }
        public string Properties12 { get; set; }
        public string Properties13 { get; set; }
        public string Properties14 { get; set; }
        public string Properties15 { get; set; }
        public string Properties16 { get; set; }
        public string Properties17 { get; set; }
        public string Properties18 { get; set; }
        public string Properties19 { get; set; }
        public string Properties20 { get; set; }
        public string Properties21 { get; set; }
        public string Properties22 { get; set; }
        public string Properties23 { get; set; }
        public string Properties24 { get; set; }
        public string Properties25 { get; set; }
        public string Properties26 { get; set; }
        public string Properties27 { get; set; }
        public string Properties28 { get; set; }
        public string Properties29 { get; set; }
        public string Properties30 { get; set; }
        public string Properties31 { get; set; }
        public string Properties32 { get; set; }
        public string Properties33 { get; set; }
        public string Properties34 { get; set; }
        public string Properties35 { get; set; }
        public string Properties36 { get; set; }
        public string Properties37 { get; set; }
        public string Properties38 { get; set; }
        public string Properties39 { get; set; }
        public string Properties40 { get; set; }
        public string Properties41 { get; set; }
        public string Properties42 { get; set; }
        public string Properties43 { get; set; }
        public string Properties44 { get; set; }
        public string Properties45 { get; set; }
        public string Properties46 { get; set; }
        public string Properties47 { get; set; }
        public string Properties48 { get; set; }
        public string Properties49 { get; set; }
        public string Properties50 { get; set; }
        public string Properties51 { get; set; }
        public string Properties52 { get; set; }
        public string Properties53 { get; set; }
        public string Properties54 { get; set; }
        public string Properties55 { get; set; }
        public string Properties56 { get; set; }
        public string Properties57 { get; set; }
        public string Properties58 { get; set; }
        public string Properties59 { get; set; }
        public string Properties60 { get; set; }
        public string Properties61 { get; set; }
        public string Properties62 { get; set; }
        public string Properties63 { get; set; }
        public string Properties64 { get; set; }
        //public string AutoCreateSerialNumbersOnRelease { get; set; }
        //public int DNFEntry { get; set; }
        //public object GTSItemSpec { get; set; }
        //public object GTSItemTaxCategory { get; set; }
        //public object FuelID { get; set; }
        //public string BeverageTableCode { get; set; }
        //public string BeverageGroupCode { get; set; }
        //public object BeverageCommercialBrandCode { get; set; }
        //public int Series { get; set; }
        //public object ToleranceDays { get; set; }
        //public string TypeOfAdvancedRules { get; set; }
        //public string IssuePrimarilyBy { get; set; }
        //public string NoDiscounts { get; set; }
        //public string AssetClass { get; set; }
        //public string AssetGroup { get; set; }
        //public string InventoryNumber { get; set; }
        //public object Technician { get; set; }
        //public object Employee { get; set; }
        //public object Location { get; set; }
        //public string AssetStatus { get; set; }
        //public object CapitalizationDate { get; set; }
        //public string StatisticalAsset { get; set; }
        //public string Cession { get; set; }
        //public string DeactivateAfterUsefulLife { get; set; }
        //public string ManageByQuantity { get; set; }
        //public int UoMGroupEntry { get; set; }
        //public object InventoryUoMEntry { get; set; }
        //public object DefaultSalesUoMEntry { get; set; }
        //public object DefaultPurchasingUoMEntry { get; set; }
        //public object DepreciationGroup { get; set; }
        //public string AssetSerialNumber { get; set; }
        //public object InventoryWeight { get; set; }
        //public object InventoryWeightUnit { get; set; }
        //public object InventoryWeight1 { get; set; }
        //public object InventoryWeightUnit1 { get; set; }
        //public object DefaultCountingUnit { get; set; }
        //public float CountingItemsPerUnit { get; set; }
        //public object DefaultCountingUoMEntry { get; set; }
        public string Excisable { get; set; }
        public int ChapterID { get; set; }
        public object ScsCode { get; set; }
        public object SpProdType { get; set; }
        public float ProdStdCost { get; set; }
        public string InCostRollup { get; set; }
        public string VirtualAssetItem { get; set; }
        public string EnforceAssetSerialNumbers { get; set; }
        public object AttachmentEntry { get; set; }
        public object LinkedResource { get; set; }
        public string GSTRelevnt { get; set; }
        public int SACEntry { get; set; }
        public string GSTTaxCategory { get; set; }
        public object U_TIPO_BIEN { get; set; }
        public string U_ICE { get; set; }
        public object U_COD_ICE_PRODUC { get; set; }
        public object U_CLASIF_ICE { get; set; }
        public object U_MARCA_ICE { get; set; }
        public object U_PRESENTACION { get; set; }
        public object U_CAPACIDAD { get; set; }
        public object U_UNID_ICE { get; set; }
        public object U_GRADO_ALC { get; set; }
        public object U_PAIS_ICE { get; set; }
        public string U_CXS_ISGC { get; set; }
        public string U_EXX_FE_InfoAdic { get; set; }
        public object U_EXX_FE_TipoInfoAdi { get; set; }
        //public Itemprice[] ItemPrices { get; set; }
        public Itemwarehouseinfocollection[] ItemWarehouseInfoCollection { get; set; }
        //public Itempreferredvendor[] ItemPreferredVendors { get; set; }
        //public object[] ItemLocalizationInfos { get; set; }
        //public object[] ItemProjects { get; set; }
        //public object[] ItemDistributionRules { get; set; }
        //public object[] ItemAttributeGroups { get; set; }
        //public object[] ItemDepreciationParameters { get; set; }
        //public object[] ItemPeriodControls { get; set; }
        //public object[] ItemUnitOfMeasurementCollection { get; set; }
        //public object[] ItemBarCodeCollection { get; set; }
        //public Itemintrastatextension ItemIntrastatExtension { get; set; }
    }

    public class Itemintrastatextension
    {
    }

    public class Itemprice
    {
        public int PriceList { get; set; }
        public float Price { get; set; }
        public object Currency { get; set; }
        public float AdditionalPrice1 { get; set; }
        public object AdditionalCurrency1 { get; set; }
        public float AdditionalPrice2 { get; set; }
        public object AdditionalCurrency2 { get; set; }
        public int BasePriceList { get; set; }
        public float Factor { get; set; }
        public object[] UoMPrices { get; set; }
    }

    public class Itemwarehouseinfocollection
    {
        public float MinimalStock { get; set; }
        public float MaximalStock { get; set; }
        public float MinimalOrder { get; set; }
        public float StandardAveragePrice { get; set; }
        public string Locked { get; set; }
        public string InventoryAccount { get; set; }
        public string CostAccount { get; set; }
        public string TransferAccount { get; set; }
        public string RevenuesAccount { get; set; }
        public string VarienceAccount { get; set; }
        public string DecreasingAccount { get; set; }
        public string IncreasingAccount { get; set; }
        public string ReturningAccount { get; set; }
        public string ExpensesAccount { get; set; }
        public string EURevenuesAccount { get; set; }
        public string EUExpensesAccount { get; set; }
        public string ForeignRevenueAcc { get; set; }
        public string ForeignExpensAcc { get; set; }
        public string ExemptIncomeAcc { get; set; }
        public string PriceDifferenceAcc { get; set; }
        public string WarehouseCode { get; set; }
        public float InStock { get; set; }
        public float Committed { get; set; }
        public float Ordered { get; set; }
        public float CountedQuantity { get; set; }
        public string WasCounted { get; set; }
        public int UserSignature { get; set; }
        public float Counted { get; set; }
        public string ExpenseClearingAct { get; set; }
        public string PurchaseCreditAcc { get; set; }
        public string EUPurchaseCreditAcc { get; set; }
        public string ForeignPurchaseCreditAcc { get; set; }
        public string SalesCreditAcc { get; set; }
        public string SalesCreditEUAcc { get; set; }
        public string ExemptedCredits { get; set; }
        public string SalesCreditForeignAcc { get; set; }
        public string ExpenseOffsettingAccount { get; set; }
        public string WipAccount { get; set; }
        public string ExchangeRateDifferencesAcct { get; set; }
        public string GoodsClearingAcct { get; set; }
        public string NegativeInventoryAdjustmentAccount { get; set; }
        public string CostInflationOffsetAccount { get; set; }
        public string GLDecreaseAcct { get; set; }
        public string GLIncreaseAcct { get; set; }
        public string PAReturnAcct { get; set; }
        public string PurchaseAcct { get; set; }
        public string PurchaseOffsetAcct { get; set; }
        public string ShippedGoodsAccount { get; set; }
        public string StockInflationOffsetAccount { get; set; }
        public string StockInflationAdjustAccount { get; set; }
        public string VATInRevenueAccount { get; set; }
        public string WipVarianceAccount { get; set; }
        public string CostInflationAccount { get; set; }
        public string WHIncomingCenvatAccount { get; set; }
        public string WHOutgoingCenvatAccount { get; set; }
        public string StockInTransitAccount { get; set; }
        public string WipOffsetProfitAndLossAccount { get; set; }
        public string InventoryOffsetProfitAndLossAccount { get; set; }
        public object DefaultBin { get; set; }
        public string DefaultBinEnforced { get; set; }
        public string PurchaseBalanceAccount { get; set; }
        public object[] ItemCycleCounts { get; set; }
    }

    public class Itempreferredvendor
    {
        public string BPCode { get; set; }
    }

}