using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IntegradorSAP.Data.Models
{
    /// <summary>
    /// InventoryGenExits SSL
    /// </summary>
    public class SalidasInventarioViewModel
    {
        public long DocEntry { get; set; }
        public long DocNum { get; set; }
        public string DocType { get; set; }
        public string HandWritten { get; set; }
        public string Printed { get; set; }
        public DateTime DocDate { get; set; }
        public string DocDueDate { get; set; }
        public object CardCode { get; set; }
        public object CardName { get; set; }
        public object Address { get; set; }
        public object NumAtCard { get; set; }
        public float DocTotal { get; set; }
        public object AttachmentEntry { get; set; }
        public string DocCurrency { get; set; }
        public float DocRate { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Comments { get; set; }
        public string JournalMemo { get; set; }
        public int PaymentGroupCode { get; set; }
        public string DocTime { get; set; }
        public int SalesPersonCode { get; set; }
        public int TransportationCode { get; set; }
        public string Confirmed { get; set; }
        public object ImportFileNum { get; set; }
        public string SummeryType { get; set; }
        public int ContactPersonCode { get; set; }
        public string ShowSCN { get; set; }
        public int Series { get; set; }
        public string TaxDate { get; set; }
        public string PartialSupply { get; set; }
        public string DocObjectCode { get; set; }
        public object ShipToCode { get; set; }
        public object Indicator { get; set; }
        public object FederalTaxID { get; set; }
        public float DiscountPercent { get; set; }
        public object PaymentReference { get; set; }
        public string CreationDate { get; set; }
        public string UpdateDate { get; set; }
        public int FinancialPeriod { get; set; }
        public int TransNum { get; set; }
        public float VatSum { get; set; }
        public float VatSumSys { get; set; }
        public float VatSumFc { get; set; }
        public string NetProcedure { get; set; }
        public float DocTotalFc { get; set; }
        public float DocTotalSys { get; set; }
        public object Form1099 { get; set; }
        public object Box1099 { get; set; }
        public string RevisionPo { get; set; }
        public object RequriedDate { get; set; }
        public object CancelDate { get; set; }
        public string BlockDunning { get; set; }
        public string Submitted { get; set; }
        public int Segment { get; set; }
        public string PickStatus { get; set; }
        public string Pick { get; set; }
        public object PaymentMethod { get; set; }
        public string PaymentBlock { get; set; }
        public object PaymentBlockEntry { get; set; }
        public object CentralBankIndicator { get; set; }
        public string MaximumCashDiscount { get; set; }
        public string Reserve { get; set; }
        public object Project { get; set; }
        public object ExemptionValidityDateFrom { get; set; }
        public object ExemptionValidityDateTo { get; set; }
        public string WareHouseUpdateType { get; set; }
        public string Rounding { get; set; }
        public object ExternalCorrectedDocNum { get; set; }
        public object InternalCorrectedDocNum { get; set; }
        public object NextCorrectingDocument { get; set; }
        public string DeferredTax { get; set; }
        public object TaxExemptionLetterNum { get; set; }
        public float WTApplied { get; set; }
        public float WTAppliedFC { get; set; }
        public string BillOfExchangeReserved { get; set; }
        public object AgentCode { get; set; }
        public float WTAppliedSC { get; set; }
        public float TotalEqualizationTax { get; set; }
        public float TotalEqualizationTaxFC { get; set; }
        public float TotalEqualizationTaxSC { get; set; }
        public int NumberOfInstallments { get; set; }
        public object ApplyTaxOnFirstInstallment { get; set; }
        public float WTNonSubjectAmount { get; set; }
        public float WTNonSubjectAmountSC { get; set; }
        public float WTNonSubjectAmountFC { get; set; }
        public float WTExemptedAmount { get; set; }
        public float WTExemptedAmountSC { get; set; }
        public float WTExemptedAmountFC { get; set; }
        public float BaseAmount { get; set; }
        public float BaseAmountSC { get; set; }
        public float BaseAmountFC { get; set; }
        public float WTAmount { get; set; }
        public float WTAmountSC { get; set; }
        public float WTAmountFC { get; set; }
        public object VatDate { get; set; }
        public object DocumentsOwner { get; set; }
        public object FolioPrefixString { get; set; }
        public int FolioNumber { get; set; }
        public string DocumentSubType { get; set; }
        public object BPChannelCode { get; set; }
        public object BPChannelContact { get; set; }
        public object Address2 { get; set; }
        public string DocumentStatus { get; set; }
        public string PeriodIndicator { get; set; }
        public object PayToCode { get; set; }
        public object ManualNumber { get; set; }
        public string UseShpdGoodsAct { get; set; }
        public object IsPayToBank { get; set; }
        public object PayToBankCountry { get; set; }
        public object PayToBankCode { get; set; }
        public object PayToBankAccountNo { get; set; }
        public object PayToBankBranch { get; set; }
        public object BPL_IDAssignedToInvoice { get; set; }
        public float DownPayment { get; set; }
        public string ReserveInvoice { get; set; }
        public object LanguageCode { get; set; }
        public object TrackingNumber { get; set; }
        public object PickRemark { get; set; }
        public object ClosingDate { get; set; }
        public object SequenceCode { get; set; }
        public object SequenceSerial { get; set; }
        public object SeriesString { get; set; }
        public object SubSeriesString { get; set; }
        public string SequenceModel { get; set; }
        public string UseCorrectionVATGroup { get; set; }
        public float TotalDiscount { get; set; }
        public float DownPaymentAmount { get; set; }
        public float DownPaymentPercentage { get; set; }
        public string DownPaymentType { get; set; }
        public float DownPaymentAmountSC { get; set; }
        public float DownPaymentAmountFC { get; set; }
        public float VatPercent { get; set; }
        public float ServiceGrossProfitPercent { get; set; }
        public object OpeningRemarks { get; set; }
        public object ClosingRemarks { get; set; }
        public float RoundingDiffAmount { get; set; }
        public float RoundingDiffAmountFC { get; set; }
        public float RoundingDiffAmountSC { get; set; }
        public string Cancelled { get; set; }
        public object SignatureInputMessage { get; set; }
        public object SignatureDigest { get; set; }
        public object CertificationNumber { get; set; }
        public object PrivateKeyVersion { get; set; }
        public object ControlAccount { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string ArchiveNonremovableSalesQuotation { get; set; }
        public object GTSChecker { get; set; }
        public object GTSPayee { get; set; }
        public object ExtraMonth { get; set; }
        public object ExtraDays { get; set; }
        public int CashDiscountDateOffset { get; set; }
        public object StartFrom { get; set; }
        public string NTSApproved { get; set; }
        public object ETaxWebSite { get; set; }
        public object ETaxNumber { get; set; }
        public object NTSApprovedNumber { get; set; }
        public string EDocGenerationType { get; set; }
        public object EDocSeries { get; set; }
        public object EDocNum { get; set; }
        public object EDocExportFormat { get; set; }
        public string EDocStatus { get; set; }
        public object EDocErrorCode { get; set; }
        public object EDocErrorMessage { get; set; }
        public string DownPaymentStatus { get; set; }
        public object GroupSeries { get; set; }
        public object GroupNumber { get; set; }
        public string GroupHandWritten { get; set; }
        public object ReopenOriginalDocument { get; set; }
        public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        public string CreateOnlineQuotation { get; set; }
        public object POSEquipmentNumber { get; set; }
        public object POSManufacturerSerialNumber { get; set; }
        public object POSCashierNumber { get; set; }
        public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        public string ClosingOption { get; set; }
        public object SpecifiedClosingDate { get; set; }
        public string OpenForLandedCosts { get; set; }
        public string AuthorizationStatus { get; set; }
        public float TotalDiscountFC { get; set; }
        public float TotalDiscountSC { get; set; }
        public string RelevantToGTS { get; set; }
        public object BPLName { get; set; }
        public object VATRegNum { get; set; }
        public object AnnualInvoiceDeclarationReference { get; set; }
        public object Supplier { get; set; }
        public object Releaser { get; set; }
        public object Receiver { get; set; }
        public object BlanketAgreementNumber { get; set; }
        public string IsAlteration { get; set; }
        public string CancelStatus { get; set; }
        public object AssetValueDate { get; set; }
        public string DocumentDelivery { get; set; }
        public object AuthorizationCode { get; set; }
        public object StartDeliveryDate { get; set; }
        public object StartDeliveryTime { get; set; }
        public object EndDeliveryDate { get; set; }
        public object EndDeliveryTime { get; set; }
        public object VehiclePlate { get; set; }
        public object ATDocumentType { get; set; }
        public object ElecCommStatus { get; set; }
        public object ElecCommMessage { get; set; }
        public string ReuseDocumentNum { get; set; }
        public string ReuseNotaFiscalNum { get; set; }
        public string PrintSEPADirect { get; set; }
        public object FiscalDocNum { get; set; }
        public object POSDailySummaryNo { get; set; }
        public object POSReceiptNo { get; set; }
        public object PointOfIssueCode { get; set; }
        public object Letter { get; set; }
        public object FolioNumberFrom { get; set; }
        public object FolioNumberTo { get; set; }
        public string InterimType { get; set; }
        public int RelatedType { get; set; }
        public object RelatedEntry { get; set; }
        public object U_SER_EST { get; set; }
        public object U_SER_PE { get; set; }
        public object U_NUM_AUTOR { get; set; }
        public string U_COD_ST { get; set; }
        public object U_SER_EST_FR { get; set; }
        public object U_SER_PEFR { get; set; }
        public object U_NUM_AUT_FR { get; set; }
        public object U_NUM_FAC_REL { get; set; }
        public object U_COMP_RET { get; set; }
        public object U_SERIE_RET { get; set; }
        public object U_NUM_AUT_RET { get; set; }
        public object U_FEC_INI_TRAS { get; set; }
        public object U_FEC_FIN_TRAS { get; set; }
        public object U_fecha_emi_doc_rel { get; set; }
        public object U_NUM_DECLAR_ADU { get; set; }
        public object U_MOT_TRASLADO { get; set; }
        public object U_PUNTO_PART { get; set; }
        public object U_NUM_GUIA { get; set; }
        public object U_CORRELATIVO { get; set; }
        public object U_VERIFICADOR { get; set; }
        public string U_TRANSPORTE { get; set; }
        public string U_TRANSPORTISTA { get; set; }
        public object U_FECHA_EMBARQUE { get; set; }
      //  public string U_Exx_IP_Pago { get; set; }
        public string U_Exx_IP_Pais { get; set; }
        public string U_Exx_IP_DobleTrib { get; set; }
        public string U_Exx_IP_SujetRet_NL { get; set; }
        public object U_Exx_FechaRet { get; set; }
        public object U_Exx_Rembolso { get; set; }
        public object U_Exx_FPagxDoc { get; set; }
        public object U_TIP_DOC_APLIC { get; set; }
        public object U_tipo_export { get; set; }
        public object U_tipo_comprob { get; set; }
        public string U_DOC_DECLARABLE { get; set; }
        public string U_DISTRITO_ADU { get; set; }
        public object U_REFRENDO_ANIO { get; set; }
        public string U_REFRENDO_REG { get; set; }
        public float U_VALOR_FOB { get; set; }
        public object U_NUM_DOC_TRANSP { get; set; }
        public object U_NUM_FUE { get; set; }
        public string U_MOT_NC { get; set; }
        public object U_MOT_ND { get; set; }
        public string U_EXX_FE_TIPCOM { get; set; }
        public string U_EXX_FE_TIPAMB { get; set; }
        public object U_EXX_FE_CODNUM { get; set; }
        public string U_EXX_FE_TIPEMI { get; set; }
        public object U_EXX_FE_DIFVER { get; set; }
        public object U_EXX_FE_FECAUT { get; set; }
        public string U_Exx_Din_Cons { get; set; }
        public object U_Exx_FE_Paisdestin { get; set; }
        public string U_Exx_pagoRegFis { get; set; }
        public object U_Exx_fechaPagoDiv { get; set; }
        public float U_Exx_imRentaSoc { get; set; }
        public object U_Exx_anioUtDiv { get; set; }
        public object U_Exx_numCajBan { get; set; }
        public float U_Exx_precCajBan { get; set; }
        public object U_EXX_CAIM { get; set; }
        public object U_EXX_Hora_Lleg { get; set; }
        public object U_EXX_Hora_Sal { get; set; }
        public string U_Exx_doc_compensac { get; set; }
        public object U_EXX_FPAGO_VENTAS { get; set; }
        public string U_EXX_FACT_NEG { get; set; }
        public object U_EXX_FPAGO_COMPRAS { get; set; }
        public object U_EXX_COMPENSADO { get; set; }
        public float U_EXX_VAL_COMP { get; set; }
        public object U_Exx_DenoFiscal { get; set; }
        public object U_Exx_ingFueGra_IR { get; set; }
        public object U_Exx_Paraiso_Fis { get; set; }
        public object U_Exx_TipIngExt { get; set; }
        public object U_Exx_TipRegFis { get; set; }
        public float U_Exx_ValoImpExt { get; set; }
        public object U_EXX_MAN_AG { get; set; }
        public object U_EXX_TIPO_TRANSACC { get; set; }
        public string U_EXX_DOC_GEN { get; set; }
        public object U_EXX_FE_DESERR { get; set; }
        public object U_EXX_FE_CODERR { get; set; }
        public string U_EXX_FE_Estado { get; set; }
        public object U_EXX_FE_ClaAcc { get; set; }
        public object U_EXX_Serie_Guia { get; set; }
        public string U_EXX_FE_PdfCreado { get; set; }
        public object U_EXX_FE_PdfError { get; set; }
        public string U_EXX_FE_MailEnviado { get; set; }
        public object U_EXX_FE_MailError { get; set; }
        public object U_EXX_FE_Reemb { get; set; }
        public object U_Exx_FE_ComExt { get; set; }
        public object U_Exx_FE_IncoTermFac { get; set; }
        public object U_Exx_FE_LugIncoTerm { get; set; }
        public object U_Exx_FE_PaisOrigen { get; set; }
        public object U_Exx_FE_PuertoEmb { get; set; }
        public object U_Exx_FE_PuertoDest { get; set; }
        public object U_Exx_FE_Paisadquis { get; set; }
        public object U_Exx_FE_Incotermto { get; set; }
        public object U_Exx_FE_Fleteinter { get; set; }
        public object U_Exx_FE_Segurointe { get; set; }
        public object U_EXX_CONTENEDOR { get; set; }
        public string U_LocalCtaContab { get; set; }
        public object U_CLAVE_ACCESO { get; set; }
        public string U_ESTADO_AUTORIZACIO { get; set; }
        public object U_NUM_AUTO_FAC { get; set; }
        public object U_FECHA_AUT_FACT { get; set; }
        public object U_OBSERVACION_FACT { get; set; }
        public string U_SSCREADAR { get; set; }
        public object U_SSIDDOCUMENTO { get; set; }
        public object U_HRH_Serie { get; set; }
        public object U_HRH_Modo_Fact { get; set; }
        public object U_HRH_Lote { get; set; }
        public object U_LQ_CLAVE { get; set; }
        public string U_LQ_ESTADO { get; set; }
        public object U_LQ_NUM_AUTO { get; set; }
        public object U_LQ_FECHA_AUT { get; set; }
        public object U_LQ_OBSERVACION { get; set; }
        public object U_DOC_REF { get; set; }
        public object[] Document_ApprovalRequests { get; set; }
        public DocumentlineSalidaViewModel[] DocumentLines { get; set; }
    
    }

  
    public class DocumentlineSalidaViewModel
    {
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public float Quantity { get; set; }
        public object ShipDate { get; set; }
        public float Price { get; set; }
        public float PriceAfterVAT { get; set; }
        public string Currency { get; set; }
        public object Rate { get; set; }
        public float DiscountPercent { get; set; }
        public string VendorNum { get; set; }
        public object SerialNum { get; set; }
        public string WarehouseCode { get; set; }
        public int SalesPersonCode { get; set; }
        public float CommisionPercent { get; set; }
        public string TreeType { get; set; }
        public string AccountCode { get; set; }
        public string UseBaseUnits { get; set; }
        public object SupplierCatNum { get; set; }
        public string CostingCode { get; set; }
        public string ProjectCode { get; set; }
        public string BarCode { get; set; }
        public object VatGroup { get; set; }
        public float Height1 { get; set; }
        public object Hight1Unit { get; set; }
        public float Height2 { get; set; }
        public object Height2Unit { get; set; }
        public float Lengh1 { get; set; }
        public object Lengh1Unit { get; set; }
        public float Lengh2 { get; set; }
        public object Lengh2Unit { get; set; }
        public float Weight1 { get; set; }
        public object Weight1Unit { get; set; }
        public float Weight2 { get; set; }
        public object Weight2Unit { get; set; }
        public float Factor1 { get; set; }
        public float Factor2 { get; set; }
        public float Factor3 { get; set; }
        public float Factor4 { get; set; }
        public int BaseType { get; set; }
        public object BaseEntry { get; set; }
        public object BaseLine { get; set; }
        public float Volume { get; set; }
        public object VolumeUnit { get; set; }
        public float Width1 { get; set; }
        public object Width1Unit { get; set; }
        public float Width2 { get; set; }
        public object Width2Unit { get; set; }
        public object Address { get; set; }
        public object TaxCode { get; set; }
        public object TaxType { get; set; }
        public object TaxLiable { get; set; }
        public string PickStatus { get; set; }
        public float PickQuantity { get; set; }
        public object PickListIdNumber { get; set; }
        public object OriginalItem { get; set; }
        public object BackOrder { get; set; }
        public object FreeText { get; set; }
        public int ShippingMethod { get; set; }
        public object POTargetNum { get; set; }
        public object POTargetEntry { get; set; }
        public object POTargetRowNum { get; set; }
        public string CorrectionInvoiceItem { get; set; }
        public float CorrInvAmountToStock { get; set; }
        public float CorrInvAmountToDiffAcct { get; set; }
        public float AppliedTax { get; set; }
        public float AppliedTaxFC { get; set; }
        public float AppliedTaxSC { get; set; }
        public object WTLiable { get; set; }
        public string DeferredTax { get; set; }
        public float EqualizationTaxPercent { get; set; }
        public float TotalEqualizationTax { get; set; }
        public float TotalEqualizationTaxFC { get; set; }
        public float TotalEqualizationTaxSC { get; set; }
        public float NetTaxAmount { get; set; }
        public float NetTaxAmountFC { get; set; }
        public float NetTaxAmountSC { get; set; }
        public string MeasureUnit { get; set; }
        public float UnitsOfMeasurment { get; set; }
        public float LineTotal { get; set; }
        public float TaxPercentagePerRow { get; set; }
        public float TaxTotal { get; set; }
        public object ConsumerSalesForecast { get; set; }
        public float ExciseAmount { get; set; }
        public float TaxPerUnit { get; set; }
        public float TotalInclTax { get; set; }
        public object CountryOrg { get; set; }
        public object SWW { get; set; }
        public object TransactionType { get; set; }
        public object DistributeExpense { get; set; }
        public object ShipToCode { get; set; }
        public float RowTotalFC { get; set; }
        public float RowTotalSC { get; set; }
        public float LastBuyInmPrice { get; set; }
        public float LastBuyDistributeSumFc { get; set; }
        public float LastBuyDistributeSumSc { get; set; }
        public float LastBuyDistributeSum { get; set; }
        public float StockDistributesumForeign { get; set; }
        public float StockDistributesumSystem { get; set; }
        public float StockDistributesum { get; set; }
        public float StockInmPrice { get; set; }
        public string PickStatusEx { get; set; }
        public float TaxBeforeDPM { get; set; }
        public float TaxBeforeDPMFC { get; set; }
        public float TaxBeforeDPMSC { get; set; }
        public object CFOPCode { get; set; }
        public object CSTCode { get; set; }
        public object Usage { get; set; }
        public object TaxOnly { get; set; }
        public int VisualOrder { get; set; }
        public float BaseOpenQuantity { get; set; }
        public float UnitPrice { get; set; }
        public string LineStatus { get; set; }
        public float PackageQuantity { get; set; }
        public object Text { get; set; }
        public string LineType { get; set; }
        public object COGSCostingCode { get; set; }
        public object COGSAccountCode { get; set; }
        public object ChangeAssemlyBoMWarehouse { get; set; }
        public float GrossBuyPrice { get; set; }
        public object GrossBase { get; set; }
        public float GrossProfitTotalBasePrice { get; set; }
        public string CostingCode2 { get; set; }
        public string CostingCode3 { get; set; }
        public string CostingCode4 { get; set; }
        public string CostingCode5 { get; set; }
        public object ItemDetails { get; set; }
        public object LocationCode { get; set; }
        public object ActualDeliveryDate { get; set; }
        public float RemainingOpenQuantity { get; set; }
        public float OpenAmount { get; set; }
        public float OpenAmountFC { get; set; }
        public float OpenAmountSC { get; set; }
        public object ExLineNo { get; set; }
        public object RequiredDate { get; set; }
        public float RequiredQuantity { get; set; }
        public object COGSCostingCode2 { get; set; }
        public object COGSCostingCode3 { get; set; }
        public object COGSCostingCode4 { get; set; }
        public object COGSCostingCode5 { get; set; }
        public object CSTforIPI { get; set; }
        public object CSTforPIS { get; set; }
        public object CSTforCOFINS { get; set; }
        public object CreditOriginCode { get; set; }
        public string WithoutInventoryMovement { get; set; }
        public object AgreementNo { get; set; }
        public object AgreementRowNumber { get; set; }
        public object ShipToDescription { get; set; }
        public object ActualBaseEntry { get; set; }
        public object ActualBaseLine { get; set; }
        public int DocEntry { get; set; }
        public object Surpluses { get; set; }
        public object DefectAndBreakup { get; set; }
        public object Shortages { get; set; }
        public string ConsiderQuantity { get; set; }
        public string PartialRetirement { get; set; }
        public float RetirementQuantity { get; set; }
        public float RetirementAPC { get; set; }
        public string ThirdParty { get; set; }
        public object ExpenseType { get; set; }
        public object ReceiptNumber { get; set; }
        public object ExpenseOperationType { get; set; }
        public object FederalTaxID { get; set; }
        public int UoMEntry { get; set; }
        public string UoMCode { get; set; }
        public float InventoryQuantity { get; set; }
        public float RemainingOpenInventoryQuantity { get; set; }
        public object ParentLineNum { get; set; }
        public int Incoterms { get; set; }
        public int TransportMode { get; set; }
        public string ItemType { get; set; }
        public string ChangeInventoryQuantityIndependently { get; set; }
        public object FreeOfChargeBP { get; set; }
        public float U_EXX_FE_ValICEVta { get; set; }
        public float U_EXX_FE_PorICEVta { get; set; }
        public object U_EXX_C_PATRIMONIO { get; set; }
        public object U_DetGlosaMrk { get; set; }
        public float U_CantCont { get; set; }
        public object[] LineTaxJurisdictions { get; set; }
        public object[] SerialNumbers { get; set; }
        public object[] BatchNumbers { get; set; }
        public object[] DocumentLinesBinAllocations { get; set; }
    }



    public class SalidasInventarioGuardarViewModel
    {
        public string CompanyDB { get; set; }
        public long DocEntry { get; set; } //
        public long DocNum { get; set; }
      
        public ContenedorGuardar ContenedorData { get; set; }
        public DateTime DocDate { get; set; }
        public DateTime DocDueDate { get; set; }
        public object CardCode { get; set; }
       
        public object NumAtCard { get; set; }
      
        public float DocRate { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Comments { get; set; }
        public string JournalMemo { get; set; }
    
        public int SalesPersonCode { get; set; }
        public string TaxDate { get; set; }
        public object RequriedDate { get; set; }
        public object CancelDate { get; set; }
        public object Project { get; set; }
        public object GroupNumber { get; set; }  //-1   
        public string U_DOC_DECLARABLE { get; set; }
        public object U_EXX_TIPO_TRANSACC { get; set; }
        public string U_EXX_DOC_GEN { get; set; }
        public string U_EXX_CONTENEDOR { get; set; }
        public string U_LocalCtaContab { get; set; }


        //public string DocType { get; set; }
        //public string HandWritten { get; set; }
        //public string Printed { get; set; }
        //public object CardName { get; set; }
        //public object Address { get; set; }
        //public float DocTotal { get; set; }
        //public object AttachmentEntry { get; set; }
        //public string DocCurrency { get; set; }
        //public int PaymentGroupCode { get; set; }
        //public string DocTime { get; set; }
        //public int TransportationCode { get; set; }
        //public string Confirmed { get; set; }
        //public object ImportFileNum { get; set; }
        //public string SummeryType { get; set; }
        //public int ContactPersonCode { get; set; }
        //public string ShowSCN { get; set; }
        //public int Series { get; set; }

        //public string PartialSupply { get; set; }
        //public string DocObjectCode { get; set; }
        //public object ShipToCode { get; set; }
        //public object Indicator { get; set; }
        //public object FederalTaxID { get; set; }
        //public float DiscountPercent { get; set; }
        //public object PaymentReference { get; set; }
        //public string CreationDate { get; set; }
        //public string UpdateDate { get; set; }
        //public int FinancialPeriod { get; set; }
        //public int TransNum { get; set; }
        //public float VatSum { get; set; }
        //public float VatSumSys { get; set; }
        //public float VatSumFc { get; set; }
        //public string NetProcedure { get; set; }
        //public float DocTotalFc { get; set; }
        //public float DocTotalSys { get; set; }
        //public object Form1099 { get; set; }
        //public object Box1099 { get; set; }
        //public string RevisionPo { get; set; }

        //public string BlockDunning { get; set; }
        //public string Submitted { get; set; }
        //public int Segment { get; set; }
        //public string PickStatus { get; set; }
        //public string Pick { get; set; }
        //public object PaymentMethod { get; set; }
        //public string PaymentBlock { get; set; }
        //public object PaymentBlockEntry { get; set; }
        //public object CentralBankIndicator { get; set; }
        //public string MaximumCashDiscount { get; set; }
        //public string Reserve { get; set; }

        //public object ExemptionValidityDateFrom { get; set; }
        //public object ExemptionValidityDateTo { get; set; }
        //public string WareHouseUpdateType { get; set; }
        //public string Rounding { get; set; }
        //public object ExternalCorrectedDocNum { get; set; }
        //public object InternalCorrectedDocNum { get; set; }
        //public object NextCorrectingDocument { get; set; }
        //public string DeferredTax { get; set; }
        //public object TaxExemptionLetterNum { get; set; }
        //public float WTApplied { get; set; }
        //public float WTAppliedFC { get; set; }
        //public string BillOfExchangeReserved { get; set; }
        //public object AgentCode { get; set; }
        //public float WTAppliedSC { get; set; }
        //public float TotalEqualizationTax { get; set; }
        //public float TotalEqualizationTaxFC { get; set; }
        //public float TotalEqualizationTaxSC { get; set; }
        //public int NumberOfInstallments { get; set; }
        //public object ApplyTaxOnFirstInstallment { get; set; }
        //public float WTNonSubjectAmount { get; set; }
        //public float WTNonSubjectAmountSC { get; set; }
        //public float WTNonSubjectAmountFC { get; set; }
        //public float WTExemptedAmount { get; set; }
        //public float WTExemptedAmountSC { get; set; }
        //public float WTExemptedAmountFC { get; set; }
        //public float BaseAmount { get; set; }
        //public float BaseAmountSC { get; set; }
        //public float BaseAmountFC { get; set; }
        //public float WTAmount { get; set; }
        //public float WTAmountSC { get; set; }
        //public float WTAmountFC { get; set; }
        //public object VatDate { get; set; }
        //public object DocumentsOwner { get; set; }
        //public object FolioPrefixString { get; set; }
        //public int FolioNumber { get; set; }
        //public string DocumentSubType { get; set; }
        //public object BPChannelCode { get; set; }
        //public object BPChannelContact { get; set; }
        //public object Address2 { get; set; }
        //public string DocumentStatus { get; set; }
        //public string PeriodIndicator { get; set; }
        //public object PayToCode { get; set; }
        //public object ManualNumber { get; set; }
        //public string UseShpdGoodsAct { get; set; }
        //public object IsPayToBank { get; set; }
        //public object PayToBankCountry { get; set; }
        //public object PayToBankCode { get; set; }
        //public object PayToBankAccountNo { get; set; }
        //public object PayToBankBranch { get; set; }
        //public object BPL_IDAssignedToInvoice { get; set; }
        //public float DownPayment { get; set; }
        //public string ReserveInvoice { get; set; }
        //public object LanguageCode { get; set; }
        //public object TrackingNumber { get; set; }
        //public object PickRemark { get; set; }
        //public object ClosingDate { get; set; }
        //public object SequenceCode { get; set; }
        //public object SequenceSerial { get; set; }
        //public object SeriesString { get; set; }
        //public object SubSeriesString { get; set; }
        //public string SequenceModel { get; set; }
        //public string UseCorrectionVATGroup { get; set; }
        //public float TotalDiscount { get; set; }
        //public float DownPaymentAmount { get; set; }
        //public float DownPaymentPercentage { get; set; }
        //public string DownPaymentType { get; set; }
        //public float DownPaymentAmountSC { get; set; }
        //public float DownPaymentAmountFC { get; set; }
        //public float VatPercent { get; set; }
        //public float ServiceGrossProfitPercent { get; set; }
        //public object OpeningRemarks { get; set; }
        //public object ClosingRemarks { get; set; }
        //public float RoundingDiffAmount { get; set; }
        //public float RoundingDiffAmountFC { get; set; }
        //public float RoundingDiffAmountSC { get; set; }
        //public string Cancelled { get; set; }
        //public object SignatureInputMessage { get; set; }
        //public object SignatureDigest { get; set; }
        //public object CertificationNumber { get; set; }
        //public object PrivateKeyVersion { get; set; }
        //public object ControlAccount { get; set; }
        //public string InsuranceOperation347 { get; set; }
        //public string ArchiveNonremovableSalesQuotation { get; set; }
        //public object GTSChecker { get; set; }
        //public object GTSPayee { get; set; }
        //public object ExtraMonth { get; set; }
        //public object ExtraDays { get; set; }
        //public int CashDiscountDateOffset { get; set; }
        //public object StartFrom { get; set; }
        //public string NTSApproved { get; set; }
        //public object ETaxWebSite { get; set; }
        //public object ETaxNumber { get; set; }
        //public object NTSApprovedNumber { get; set; }
        //public string EDocGenerationType { get; set; }
        //public object EDocSeries { get; set; }
        //public object EDocNum { get; set; }
        //public object EDocExportFormat { get; set; }
        //public string EDocStatus { get; set; }
        //public object EDocErrorCode { get; set; }
        //public object EDocErrorMessage { get; set; }
        //public string DownPaymentStatus { get; set; }
        //public object GroupSeries { get; set; }

        //public string GroupHandWritten { get; set; }
        //public object ReopenOriginalDocument { get; set; }
        //public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        //public string CreateOnlineQuotation { get; set; }
        //public object POSEquipmentNumber { get; set; }
        //public object POSManufacturerSerialNumber { get; set; }
        //public object POSCashierNumber { get; set; }
        //public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        //public string ClosingOption { get; set; }
        //public object SpecifiedClosingDate { get; set; }
        //public string OpenForLandedCosts { get; set; }
        //public string AuthorizationStatus { get; set; }
        //public float TotalDiscountFC { get; set; }
        //public float TotalDiscountSC { get; set; }
        //public string RelevantToGTS { get; set; }
        //public object BPLName { get; set; }
        //public object VATRegNum { get; set; }
        //public object AnnualInvoiceDeclarationReference { get; set; }
        //public object Supplier { get; set; }
        //public object Releaser { get; set; }
        //public object Receiver { get; set; }
        //public object BlanketAgreementNumber { get; set; }
        //public string IsAlteration { get; set; }
        //public string CancelStatus { get; set; }
        //public object AssetValueDate { get; set; }
        //public string DocumentDelivery { get; set; }
        //public object AuthorizationCode { get; set; }
        //public object StartDeliveryDate { get; set; }
        //public object StartDeliveryTime { get; set; }
        //public object EndDeliveryDate { get; set; }
        //public object EndDeliveryTime { get; set; }
        //public object VehiclePlate { get; set; }
        //public object ATDocumentType { get; set; }
        //public object ElecCommStatus { get; set; }
        //public object ElecCommMessage { get; set; }
        //public string ReuseDocumentNum { get; set; }
        //public string ReuseNotaFiscalNum { get; set; }
        //public string PrintSEPADirect { get; set; }
        //public object FiscalDocNum { get; set; }
        //public object POSDailySummaryNo { get; set; }
        //public object POSReceiptNo { get; set; }
        //public object PointOfIssueCode { get; set; }
        //public object Letter { get; set; }
        //public object FolioNumberFrom { get; set; }
        //public object FolioNumberTo { get; set; }
        //public string InterimType { get; set; }
        //public int RelatedType { get; set; }
        //public object RelatedEntry { get; set; }
        //public object U_SER_EST { get; set; }
        //public object U_SER_PE { get; set; }
        //public object U_NUM_AUTOR { get; set; }
        //public string U_COD_ST { get; set; }
        //public object U_SER_EST_FR { get; set; }
        //public object U_SER_PEFR { get; set; }
        //public object U_NUM_AUT_FR { get; set; }
        //public object U_NUM_FAC_REL { get; set; }
        //public object U_COMP_RET { get; set; }
        //public object U_SERIE_RET { get; set; }
        //public object U_NUM_AUT_RET { get; set; }
        //public object U_FEC_INI_TRAS { get; set; }
        //public object U_FEC_FIN_TRAS { get; set; }
        //public object U_fecha_emi_doc_rel { get; set; }
        //public object U_NUM_DECLAR_ADU { get; set; }
        //public object U_MOT_TRASLADO { get; set; }
        //public object U_PUNTO_PART { get; set; }
        //public object U_NUM_GUIA { get; set; }
        //public object U_CORRELATIVO { get; set; }
        //public object U_VERIFICADOR { get; set; }
        //public string U_TRANSPORTE { get; set; }
        //public string U_TRANSPORTISTA { get; set; }
        //public object U_FECHA_EMBARQUE { get; set; }
        //public string U_Exx_IP_Pago { get; set; }
        //public string U_Exx_IP_Pais { get; set; }
        //public string U_Exx_IP_DobleTrib { get; set; }
        //public string U_Exx_IP_SujetRet_NL { get; set; }
        //public object U_Exx_FechaRet { get; set; }
        //public object U_Exx_Rembolso { get; set; }
        //public object U_Exx_FPagxDoc { get; set; }
        //public object U_TIP_DOC_APLIC { get; set; }
        //public object U_tipo_export { get; set; }
        //public object U_tipo_comprob { get; set; }

        //public string U_DISTRITO_ADU { get; set; }
        //public object U_REFRENDO_ANIO { get; set; }
        //public string U_REFRENDO_REG { get; set; }
        //public float U_VALOR_FOB { get; set; }
        //public object U_NUM_DOC_TRANSP { get; set; }
        //public object U_NUM_FUE { get; set; }
        //public string U_MOT_NC { get; set; }
        //public object U_MOT_ND { get; set; }
        //public string U_EXX_FE_TIPCOM { get; set; }
        //public string U_EXX_FE_TIPAMB { get; set; }
        //public object U_EXX_FE_CODNUM { get; set; }
        //public string U_EXX_FE_TIPEMI { get; set; }
        //public object U_EXX_FE_DIFVER { get; set; }
        //public object U_EXX_FE_FECAUT { get; set; }
        //public string U_Exx_Din_Cons { get; set; }
        //public object U_Exx_FE_Paisdestin { get; set; }
        //public string U_Exx_pagoRegFis { get; set; }
        //public object U_Exx_fechaPagoDiv { get; set; }
        //public float U_Exx_imRentaSoc { get; set; }
        //public object U_Exx_anioUtDiv { get; set; }
        //public object U_Exx_numCajBan { get; set; }
        //public float U_Exx_precCajBan { get; set; }
        //public object U_EXX_CAIM { get; set; }
        //public object U_EXX_Hora_Lleg { get; set; }
        //public object U_EXX_Hora_Sal { get; set; }
        //public string U_Exx_doc_compensac { get; set; }
        //public object U_EXX_FPAGO_VENTAS { get; set; }
        //public string U_EXX_FACT_NEG { get; set; }
        //public object U_EXX_FPAGO_COMPRAS { get; set; }
        //public object U_EXX_COMPENSADO { get; set; }
        //public float U_EXX_VAL_COMP { get; set; }
        //public object U_Exx_DenoFiscal { get; set; }
        //public object U_Exx_ingFueGra_IR { get; set; }
        //public object U_Exx_Paraiso_Fis { get; set; }
        //public object U_Exx_TipIngExt { get; set; }
        //public object U_Exx_TipRegFis { get; set; }
        //public float U_Exx_ValoImpExt { get; set; }
        //public object U_EXX_MAN_AG { get; set; }

        //public object U_EXX_FE_DESERR { get; set; }
        //public object U_EXX_FE_CODERR { get; set; }
        //public string U_EXX_FE_Estado { get; set; }
        //public object U_EXX_FE_ClaAcc { get; set; }
        //public object U_EXX_Serie_Guia { get; set; }
        //public string U_EXX_FE_PdfCreado { get; set; }
        //public object U_EXX_FE_PdfError { get; set; }
        //public string U_EXX_FE_MailEnviado { get; set; }
        //public object U_EXX_FE_MailError { get; set; }
        //public object U_EXX_FE_Reemb { get; set; }
        //public object U_Exx_FE_ComExt { get; set; }
        //public object U_Exx_FE_IncoTermFac { get; set; }
        //public object U_Exx_FE_LugIncoTerm { get; set; }
        //public object U_Exx_FE_PaisOrigen { get; set; }
        //public object U_Exx_FE_PuertoEmb { get; set; }
        //public object U_Exx_FE_PuertoDest { get; set; }
        //public object U_Exx_FE_Paisadquis { get; set; }
        //public object U_Exx_FE_Incotermto { get; set; }
        //public object U_Exx_FE_Fleteinter { get; set; }
        //public object U_Exx_FE_Segurointe { get; set; }

        //public object U_CLAVE_ACCESO { get; set; }
        //public string U_ESTADO_AUTORIZACIO { get; set; }
        //public object U_NUM_AUTO_FAC { get; set; }
        //public object U_FECHA_AUT_FACT { get; set; }
        //public object U_OBSERVACION_FACT { get; set; }
        //public string U_SSCREADAR { get; set; }
        //public object U_SSIDDOCUMENTO { get; set; }
        //public object U_HRH_Serie { get; set; }
        //public object U_HRH_Modo_Fact { get; set; }
        //public object U_HRH_Lote { get; set; }
        //public object U_LQ_CLAVE { get; set; }
        //public string U_LQ_ESTADO { get; set; }
        //public object U_LQ_NUM_AUTO { get; set; }
        //public object U_LQ_FECHA_AUT { get; set; }
        //public object U_LQ_OBSERVACION { get; set; }
        //public object U_DOC_REF { get; set; }
        //public object[] Document_ApprovalRequests { get; set; }
        public DocumentlineSalidaGuardarViewModel[] DocumentLines { get; set; }

    }

    public class DocumentlineSalidaGuardarViewModel
    {
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public float Quantity { get; set; }

        public float Price { get; set; }
        public DateTime ShipDate { get; set; }

        public string WarehouseCode { get; set; }

        public string CostingCode { get; set; }
        public string CostingCode2 { get; set; }
        public string CostingCode3 { get; set; }
        public string CostingCode4 { get; set; }
        public string CostingCode5 { get; set; }
        public string ProjectCode { get; set; }
       // public string TaxCode { get; set; }
        public string FreeText { get; set; }
        //public int SalesPersonCode { get; set; }
        //public float CommisionPercent { get; set; }
        //public string TreeType { get; set; }
        //public string AccountCode { get; set; }
        //public string UseBaseUnits { get; set; }
        //public string SupplierCatNum { get; set; }
        //public float Price { get; set; }
        //public float PriceAfterVAT { get; set; }
        //public string Currency { get; set; }
        //public float Rate { get; set; }
        //public float DiscountPercent { get; set; }
        //public string VendorNum { get; set; }
        //public string SerialNum { get; set; }
        //public object BarCode { get; set; }
        //public string VatGroup { get; set; }
        //public float Height1 { get; set; }
        //public object Hight1Unit { get; set; }
        //public float Height2 { get; set; }
        //public object Height2Unit { get; set; }
        //public float Lengh1 { get; set; }
        //public object Lengh1Unit { get; set; }
        //public float Lengh2 { get; set; }
        //public object Lengh2Unit { get; set; }
        //public float Weight1 { get; set; }
        //public object Weight1Unit { get; set; }
        //public float Weight2 { get; set; }
        //public object Weight2Unit { get; set; }
        //public float Factor1 { get; set; }
        //public float Factor2 { get; set; }
        //public float Factor3 { get; set; }
        //public float Factor4 { get; set; }
        //public int BaseType { get; set; }
        //public int BaseEntry { get; set; }
        //public int BaseLine { get; set; }
        //public float Volume { get; set; }
        //public int VolumeUnit { get; set; }
        //public float Width1 { get; set; }
        //public object Width1Unit { get; set; }
        //public float Width2 { get; set; }
        //public object Width2Unit { get; set; }
        //public string Address { get; set; }

        //public string TaxType { get; set; }
        //public string TaxLiable { get; set; }
        //public string PickStatus { get; set; }
        //public float PickQuantity { get; set; }
        //public object PickListIdNumber { get; set; }
        //public string OriginalItem { get; set; }
        //public object BackOrder { get; set; }

        //public int ShippingMethod { get; set; }
        //public object POTargetNum { get; set; }
        //public string POTargetEntry { get; set; }
        //public object POTargetRowNum { get; set; }
        //public string CorrectionInvoiceItem { get; set; }
        //public float CorrInvAmountToStock { get; set; }
        //public float CorrInvAmountToDiffAcct { get; set; }
        //public float AppliedTax { get; set; }
        //public float AppliedTaxFC { get; set; }
        //public float AppliedTaxSC { get; set; }
        //public string WTLiable { get; set; }
        //public string DeferredTax { get; set; }
        //public float EqualizationTaxPercent { get; set; }
        //public float TotalEqualizationTax { get; set; }
        //public float TotalEqualizationTaxFC { get; set; }
        //public float TotalEqualizationTaxSC { get; set; }
        //public float NetTaxAmount { get; set; }
        //public float NetTaxAmountFC { get; set; }
        //public float NetTaxAmountSC { get; set; }
  //      public string MeasureUnit { get; set; }
   //     public float UnitsOfMeasurment { get; set; }
        //public float LineTotal { get; set; }
        //public float TaxPercentagePerRow { get; set; }
        //public float TaxTotal { get; set; }
        //public string ConsumerSalesForecast { get; set; }
        //public float ExciseAmount { get; set; }
        //public float TaxPerUnit { get; set; }
        //public float TotalInclTax { get; set; }
        //public object CountryOrg { get; set; }
        //public string SWW { get; set; }
        //public object TransactionType { get; set; }
        //public string DistributeExpense { get; set; }
        //public object ShipToCode { get; set; }
        //public float RowTotalFC { get; set; }
        //public float RowTotalSC { get; set; }
        //public float LastBuyInmPrice { get; set; }
        //public float LastBuyDistributeSumFc { get; set; }
        //public float LastBuyDistributeSumSc { get; set; }
        //public float LastBuyDistributeSum { get; set; }
        //public float StockDistributesumForeign { get; set; }
        //public float StockDistributesumSystem { get; set; }
        //public float StockDistributesum { get; set; }
        //public float StockInmPrice { get; set; }
        //public string PickStatusEx { get; set; }
        //public float TaxBeforeDPM { get; set; }
        //public float TaxBeforeDPMFC { get; set; }
        //public float TaxBeforeDPMSC { get; set; }
        //public object CFOPCode { get; set; }
        //public object CSTCode { get; set; }
        //public object Usage { get; set; }
        //public string TaxOnly { get; set; }
        //public int VisualOrder { get; set; }
        //public float BaseOpenQuantity { get; set; }

        //public string LineStatus { get; set; }
        //public float PackageQuantity { get; set; }
        //public string Text { get; set; }
        //public string LineType { get; set; }
        //public object COGSCostingCode { get; set; }
        //public string COGSAccountCode { get; set; }
        //public string ChangeAssemlyBoMWarehouse { get; set; }
        //public float GrossBuyPrice { get; set; }
        //public object GrossBase { get; set; }
        //public float GrossProfitTotalBasePrice { get; set; }

        //public object ItemDetails { get; set; }
        //public object LocationCode { get; set; }
        //public object ActualDeliveryDate { get; set; }
        //public float RemainingOpenQuantity { get; set; }
        //public float OpenAmount { get; set; }
        //public float OpenAmountFC { get; set; }
        //public float OpenAmountSC { get; set; }
        //public object ExLineNo { get; set; }
        //public string RequiredDate { get; set; }
        //public float RequiredQuantity { get; set; }
        //public object COGSCostingCode2 { get; set; }
        //public object COGSCostingCode3 { get; set; }
        //public object COGSCostingCode4 { get; set; }
        //public object COGSCostingCode5 { get; set; }
        //public object CSTforIPI { get; set; }
        //public object CSTforPIS { get; set; }
        //public object CSTforCOFINS { get; set; }
        //public object CreditOriginCode { get; set; }
        //public string WithoutInventoryMovement { get; set; }
        //public object AgreementNo { get; set; }
        //public object AgreementRowNumber { get; set; }
        //public string ShipToDescription { get; set; }
        //public object ActualBaseEntry { get; set; }
        //public object ActualBaseLine { get; set; }
        //public int DocEntry { get; set; }
        //public float Surpluses { get; set; }
        //public float DefectAndBreakup { get; set; }
        //public float Shortages { get; set; }
        //public string ConsiderQuantity { get; set; }
        //public string PartialRetirement { get; set; }
        //public float RetirementQuantity { get; set; }
        //public float RetirementAPC { get; set; }
        //public string ThirdParty { get; set; }
        //public object ExpenseType { get; set; }
        //public object ReceiptNumber { get; set; }
        //public object ExpenseOperationType { get; set; }
        //public object FederalTaxID { get; set; }
        //public int UoMEntry { get; set; }
        public string UoMCode { get; set; }
        //public float InventoryQuantity { get; set; }
        //public float RemainingOpenInventoryQuantity { get; set; }
        //public object ParentLineNum { get; set; }
        //public int Incoterms { get; set; }
        //public int TransportMode { get; set; }
        //public string ItemType { get; set; }
        //public string ChangeInventoryQuantityIndependently { get; set; }
        //public object FreeOfChargeBP { get; set; }
        //public object U_EXX_FE_ValICEVta { get; set; }
        //public object U_EXX_FE_PorICEVta { get; set; }
        //public object U_EXX_C_PATRIMONIO { get; set; }
        //public object U_DetGlosaMrk { get; set; }
        //public object U_CTK_REF_LOG_INT { get; set; }
        //public Linetaxjurisdiction[] LineTaxJurisdictions { get; set; }
        //public object[] DocumentLineAdditionalExpenses { get; set; }
        //public object[] WithholdingTaxLines { get; set; }
        //public object[] SerialNumbers { get; set; }
        //public object[] BatchNumbers { get; set; }
        //public object[] DocumentLinesBinAllocations { get; set; }
    }

    public class SalidasInventarioSaveViewModel
    {
        //public string CompanyDB { get; set; }
        public long DocEntry { get; set; } //
        public long DocNum { get; set; }

        public DateTime DocDate { get; set; }
        public DateTime DocDueDate { get; set; }
        // public object CardCode { get; set; }

        public object NumAtCard { get; set; }

        // public float DocRate { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Comments { get; set; }
        public string JournalMemo { get; set; }

        //  public int SalesPersonCode { get; set; }
        public string TaxDate { get; set; }
        public object RequriedDate { get; set; }
        //   public object CancelDate { get; set; }
        public object Project { get; set; }
        // public object GroupNumber { get; set; }  //-1   
        public string U_DOC_DECLARABLE { get; set; }
        public object U_EXX_TIPO_TRANSACC { get; set; }
        //    public string U_EXX_DOC_GEN { get; set; }
        public object U_EXX_CONTENEDOR { get; set; }
        public string U_LocalCtaContab { get; set; }


        //public string DocType { get; set; }
        //public string HandWritten { get; set; }
        //public string Printed { get; set; }
        //public object CardName { get; set; }
        //public object Address { get; set; }
        //public float DocTotal { get; set; }
        //public object AttachmentEntry { get; set; }
        //public string DocCurrency { get; set; }
        //public int PaymentGroupCode { get; set; }
        //public string DocTime { get; set; }
        //public int TransportationCode { get; set; }
        //public string Confirmed { get; set; }
        //public object ImportFileNum { get; set; }
        //public string SummeryType { get; set; }
        //public int ContactPersonCode { get; set; }
        //public string ShowSCN { get; set; }
        //public int Series { get; set; }

        //public string PartialSupply { get; set; }
        //public string DocObjectCode { get; set; }
        //public object ShipToCode { get; set; }
        //public object Indicator { get; set; }
        //public object FederalTaxID { get; set; }
        //public float DiscountPercent { get; set; }
        //public object PaymentReference { get; set; }
        //public string CreationDate { get; set; }
        //public string UpdateDate { get; set; }
        //public int FinancialPeriod { get; set; }
        //public int TransNum { get; set; }
        //public float VatSum { get; set; }
        //public float VatSumSys { get; set; }
        //public float VatSumFc { get; set; }
        //public string NetProcedure { get; set; }
        //public float DocTotalFc { get; set; }
        //public float DocTotalSys { get; set; }
        //public object Form1099 { get; set; }
        //public object Box1099 { get; set; }
        //public string RevisionPo { get; set; }

        //public string BlockDunning { get; set; }
        //public string Submitted { get; set; }
        //public int Segment { get; set; }
        //public string PickStatus { get; set; }
        //public string Pick { get; set; }
        //public object PaymentMethod { get; set; }
        //public string PaymentBlock { get; set; }
        //public object PaymentBlockEntry { get; set; }
        //public object CentralBankIndicator { get; set; }
        //public string MaximumCashDiscount { get; set; }
        //public string Reserve { get; set; }

        //public object ExemptionValidityDateFrom { get; set; }
        //public object ExemptionValidityDateTo { get; set; }
        //public string WareHouseUpdateType { get; set; }
        //public string Rounding { get; set; }
        //public object ExternalCorrectedDocNum { get; set; }
        //public object InternalCorrectedDocNum { get; set; }
        //public object NextCorrectingDocument { get; set; }
        //public string DeferredTax { get; set; }
        //public object TaxExemptionLetterNum { get; set; }
        //public float WTApplied { get; set; }
        //public float WTAppliedFC { get; set; }
        //public string BillOfExchangeReserved { get; set; }
        //public object AgentCode { get; set; }
        //public float WTAppliedSC { get; set; }
        //public float TotalEqualizationTax { get; set; }
        //public float TotalEqualizationTaxFC { get; set; }
        //public float TotalEqualizationTaxSC { get; set; }
        //public int NumberOfInstallments { get; set; }
        //public object ApplyTaxOnFirstInstallment { get; set; }
        //public float WTNonSubjectAmount { get; set; }
        //public float WTNonSubjectAmountSC { get; set; }
        //public float WTNonSubjectAmountFC { get; set; }
        //public float WTExemptedAmount { get; set; }
        //public float WTExemptedAmountSC { get; set; }
        //public float WTExemptedAmountFC { get; set; }
        //public float BaseAmount { get; set; }
        //public float BaseAmountSC { get; set; }
        //public float BaseAmountFC { get; set; }
        //public float WTAmount { get; set; }
        //public float WTAmountSC { get; set; }
        //public float WTAmountFC { get; set; }
        //public object VatDate { get; set; }
        //public object DocumentsOwner { get; set; }
        //public object FolioPrefixString { get; set; }
        //public int FolioNumber { get; set; }
        //public string DocumentSubType { get; set; }
        //public object BPChannelCode { get; set; }
        //public object BPChannelContact { get; set; }
        //public object Address2 { get; set; }
        //public string DocumentStatus { get; set; }
        //public string PeriodIndicator { get; set; }
        //public object PayToCode { get; set; }
        //public object ManualNumber { get; set; }
        //public string UseShpdGoodsAct { get; set; }
        //public object IsPayToBank { get; set; }
        //public object PayToBankCountry { get; set; }
        //public object PayToBankCode { get; set; }
        //public object PayToBankAccountNo { get; set; }
        //public object PayToBankBranch { get; set; }
        //public object BPL_IDAssignedToInvoice { get; set; }
        //public float DownPayment { get; set; }
        //public string ReserveInvoice { get; set; }
        //public object LanguageCode { get; set; }
        //public object TrackingNumber { get; set; }
        //public object PickRemark { get; set; }
        //public object ClosingDate { get; set; }
        //public object SequenceCode { get; set; }
        //public object SequenceSerial { get; set; }
        //public object SeriesString { get; set; }
        //public object SubSeriesString { get; set; }
        //public string SequenceModel { get; set; }
        //public string UseCorrectionVATGroup { get; set; }
        //public float TotalDiscount { get; set; }
        //public float DownPaymentAmount { get; set; }
        //public float DownPaymentPercentage { get; set; }
        //public string DownPaymentType { get; set; }
        //public float DownPaymentAmountSC { get; set; }
        //public float DownPaymentAmountFC { get; set; }
        //public float VatPercent { get; set; }
        //public float ServiceGrossProfitPercent { get; set; }
        //public object OpeningRemarks { get; set; }
        //public object ClosingRemarks { get; set; }
        //public float RoundingDiffAmount { get; set; }
        //public float RoundingDiffAmountFC { get; set; }
        //public float RoundingDiffAmountSC { get; set; }
        //public string Cancelled { get; set; }
        //public object SignatureInputMessage { get; set; }
        //public object SignatureDigest { get; set; }
        //public object CertificationNumber { get; set; }
        //public object PrivateKeyVersion { get; set; }
        //public object ControlAccount { get; set; }
        //public string InsuranceOperation347 { get; set; }
        //public string ArchiveNonremovableSalesQuotation { get; set; }
        //public object GTSChecker { get; set; }
        //public object GTSPayee { get; set; }
        //public object ExtraMonth { get; set; }
        //public object ExtraDays { get; set; }
        //public int CashDiscountDateOffset { get; set; }
        //public object StartFrom { get; set; }
        //public string NTSApproved { get; set; }
        //public object ETaxWebSite { get; set; }
        //public object ETaxNumber { get; set; }
        //public object NTSApprovedNumber { get; set; }
        //public string EDocGenerationType { get; set; }
        //public object EDocSeries { get; set; }
        //public object EDocNum { get; set; }
        //public object EDocExportFormat { get; set; }
        //public string EDocStatus { get; set; }
        //public object EDocErrorCode { get; set; }
        //public object EDocErrorMessage { get; set; }
        //public string DownPaymentStatus { get; set; }
        //public object GroupSeries { get; set; }

        //public string GroupHandWritten { get; set; }
        //public object ReopenOriginalDocument { get; set; }
        //public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        //public string CreateOnlineQuotation { get; set; }
        //public object POSEquipmentNumber { get; set; }
        //public object POSManufacturerSerialNumber { get; set; }
        //public object POSCashierNumber { get; set; }
        //public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        //public string ClosingOption { get; set; }
        //public object SpecifiedClosingDate { get; set; }
        //public string OpenForLandedCosts { get; set; }
        //public string AuthorizationStatus { get; set; }
        //public float TotalDiscountFC { get; set; }
        //public float TotalDiscountSC { get; set; }
        //public string RelevantToGTS { get; set; }
        //public object BPLName { get; set; }
        //public object VATRegNum { get; set; }
        //public object AnnualInvoiceDeclarationReference { get; set; }
        //public object Supplier { get; set; }
        //public object Releaser { get; set; }
        //public object Receiver { get; set; }
        //public object BlanketAgreementNumber { get; set; }
        //public string IsAlteration { get; set; }
        //public string CancelStatus { get; set; }
        //public object AssetValueDate { get; set; }
        //public string DocumentDelivery { get; set; }
        //public object AuthorizationCode { get; set; }
        //public object StartDeliveryDate { get; set; }
        //public object StartDeliveryTime { get; set; }
        //public object EndDeliveryDate { get; set; }
        //public object EndDeliveryTime { get; set; }
        //public object VehiclePlate { get; set; }
        //public object ATDocumentType { get; set; }
        //public object ElecCommStatus { get; set; }
        //public object ElecCommMessage { get; set; }
        //public string ReuseDocumentNum { get; set; }
        //public string ReuseNotaFiscalNum { get; set; }
        //public string PrintSEPADirect { get; set; }
        //public object FiscalDocNum { get; set; }
        //public object POSDailySummaryNo { get; set; }
        //public object POSReceiptNo { get; set; }
        //public object PointOfIssueCode { get; set; }
        //public object Letter { get; set; }
        //public object FolioNumberFrom { get; set; }
        //public object FolioNumberTo { get; set; }
        //public string InterimType { get; set; }
        //public int RelatedType { get; set; }
        //public object RelatedEntry { get; set; }
        //public object U_SER_EST { get; set; }
        //public object U_SER_PE { get; set; }
        //public object U_NUM_AUTOR { get; set; }
        //public string U_COD_ST { get; set; }
        //public object U_SER_EST_FR { get; set; }
        //public object U_SER_PEFR { get; set; }
        //public object U_NUM_AUT_FR { get; set; }
        //public object U_NUM_FAC_REL { get; set; }
        //public object U_COMP_RET { get; set; }
        //public object U_SERIE_RET { get; set; }
        //public object U_NUM_AUT_RET { get; set; }
        //public object U_FEC_INI_TRAS { get; set; }
        //public object U_FEC_FIN_TRAS { get; set; }
        //public object U_fecha_emi_doc_rel { get; set; }
        //public object U_NUM_DECLAR_ADU { get; set; }
        //public object U_MOT_TRASLADO { get; set; }
        //public object U_PUNTO_PART { get; set; }
        //public object U_NUM_GUIA { get; set; }
        //public object U_CORRELATIVO { get; set; }
        //public object U_VERIFICADOR { get; set; }
        //public string U_TRANSPORTE { get; set; }
        //public string U_TRANSPORTISTA { get; set; }
        //public object U_FECHA_EMBARQUE { get; set; }
        //public string U_Exx_IP_Pago { get; set; }
        //public string U_Exx_IP_Pais { get; set; }
        //public string U_Exx_IP_DobleTrib { get; set; }
        //public string U_Exx_IP_SujetRet_NL { get; set; }
        //public object U_Exx_FechaRet { get; set; }
        //public object U_Exx_Rembolso { get; set; }
        //public object U_Exx_FPagxDoc { get; set; }
        //public object U_TIP_DOC_APLIC { get; set; }
        //public object U_tipo_export { get; set; }
        //public object U_tipo_comprob { get; set; }

        //public string U_DISTRITO_ADU { get; set; }
        //public object U_REFRENDO_ANIO { get; set; }
        //public string U_REFRENDO_REG { get; set; }
        //public float U_VALOR_FOB { get; set; }
        //public object U_NUM_DOC_TRANSP { get; set; }
        //public object U_NUM_FUE { get; set; }
        //public string U_MOT_NC { get; set; }
        //public object U_MOT_ND { get; set; }
        //public string U_EXX_FE_TIPCOM { get; set; }
        //public string U_EXX_FE_TIPAMB { get; set; }
        //public object U_EXX_FE_CODNUM { get; set; }
        //public string U_EXX_FE_TIPEMI { get; set; }
        //public object U_EXX_FE_DIFVER { get; set; }
        //public object U_EXX_FE_FECAUT { get; set; }
        //public string U_Exx_Din_Cons { get; set; }
        //public object U_Exx_FE_Paisdestin { get; set; }
        //public string U_Exx_pagoRegFis { get; set; }
        //public object U_Exx_fechaPagoDiv { get; set; }
        //public float U_Exx_imRentaSoc { get; set; }
        //public object U_Exx_anioUtDiv { get; set; }
        //public object U_Exx_numCajBan { get; set; }
        //public float U_Exx_precCajBan { get; set; }
        //public object U_EXX_CAIM { get; set; }
        //public object U_EXX_Hora_Lleg { get; set; }
        //public object U_EXX_Hora_Sal { get; set; }
        //public string U_Exx_doc_compensac { get; set; }
        //public object U_EXX_FPAGO_VENTAS { get; set; }
        //public string U_EXX_FACT_NEG { get; set; }
        //public object U_EXX_FPAGO_COMPRAS { get; set; }
        //public object U_EXX_COMPENSADO { get; set; }
        //public float U_EXX_VAL_COMP { get; set; }
        //public object U_Exx_DenoFiscal { get; set; }
        //public object U_Exx_ingFueGra_IR { get; set; }
        //public object U_Exx_Paraiso_Fis { get; set; }
        //public object U_Exx_TipIngExt { get; set; }
        //public object U_Exx_TipRegFis { get; set; }
        //public float U_Exx_ValoImpExt { get; set; }
        //public object U_EXX_MAN_AG { get; set; }

        //public object U_EXX_FE_DESERR { get; set; }
        //public object U_EXX_FE_CODERR { get; set; }
        //public string U_EXX_FE_Estado { get; set; }
        //public object U_EXX_FE_ClaAcc { get; set; }
        //public object U_EXX_Serie_Guia { get; set; }
        //public string U_EXX_FE_PdfCreado { get; set; }
        //public object U_EXX_FE_PdfError { get; set; }
        //public string U_EXX_FE_MailEnviado { get; set; }
        //public object U_EXX_FE_MailError { get; set; }
        //public object U_EXX_FE_Reemb { get; set; }
        //public object U_Exx_FE_ComExt { get; set; }
        //public object U_Exx_FE_IncoTermFac { get; set; }
        //public object U_Exx_FE_LugIncoTerm { get; set; }
        //public object U_Exx_FE_PaisOrigen { get; set; }
        //public object U_Exx_FE_PuertoEmb { get; set; }
        //public object U_Exx_FE_PuertoDest { get; set; }
        //public object U_Exx_FE_Paisadquis { get; set; }
        //public object U_Exx_FE_Incotermto { get; set; }
        //public object U_Exx_FE_Fleteinter { get; set; }
        //public object U_Exx_FE_Segurointe { get; set; }

        //public object U_CLAVE_ACCESO { get; set; }
        //public string U_ESTADO_AUTORIZACIO { get; set; }
        //public object U_NUM_AUTO_FAC { get; set; }
        //public object U_FECHA_AUT_FACT { get; set; }
        //public object U_OBSERVACION_FACT { get; set; }
        //public string U_SSCREADAR { get; set; }
        //public object U_SSIDDOCUMENTO { get; set; }
        //public object U_HRH_Serie { get; set; }
        //public object U_HRH_Modo_Fact { get; set; }
        //public object U_HRH_Lote { get; set; }
        //public object U_LQ_CLAVE { get; set; }
        //public string U_LQ_ESTADO { get; set; }
        //public object U_LQ_NUM_AUTO { get; set; }
        //public object U_LQ_FECHA_AUT { get; set; }
        //public object U_LQ_OBSERVACION { get; set; }
        //public object U_DOC_REF { get; set; }
        //public object[] Document_ApprovalRequests { get; set; }
        public DocumentlineSalidaGuardarViewModel[] DocumentLines { get; set; }

    }

}